apps/cart/urls.py
from django.conf.urls import url
from .views import CartDetailView, CartDetailByPkUser, CartDetailByPkShop, ConfirmOrderByShop


urlpatterns = [
    url(r'^user/(?P<username>[\w.@+-]+)/(?P<pk>\d+)/$', CartDetailByPkUser.as_view(), name='detail_by_pk_user'),
    url(r'^shop/(?P<shop_slug>[\w.@+-]+)/(?P<pk>\d+)/$', CartDetailByPkShop.as_view(), name='detail_by_pk_shop'),
    url(r'^(?P<pk>\d+)/confirm/$', ConfirmOrderByShop.as_view(), name='detail_by_pk'),
    url(r'^$', CartDetailView.as_view(), name='detail'),
]

apps/shop/urls.py
from django.conf.urls import url, include

from apps.shop.views import *

# ProductFormView

# from apps.shop.views import shop_add

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/sale/(?P<pk>[0-9]+)/$', sale_detail, name='sale_detail'),
    url(r'^delete-banners/$', delete_banners, name='delete-banners'),
    url(r'^create/$', ShopCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', ShopDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/about-us/$', ShopAboutUsDetailView.as_view(), name='about_us'),
    url(r'^(?P<slug>[\w-]+)/contacts/$', ShopContactsView.as_view(), name='contacts_detail'),
    url(r'^(?P<slug>[\w-]+)/sale/create/$', SalesCreateView.as_view(), name='add_sale'),
    url(r'^(?P<slug>[\w-]+)/sale/(?P<pk>[0-9]+)/update$', SalesUpdateView.as_view(), name='update_sale'),
    url(r'^(?P<slug>[\w-]+)/sale/$', ShopSaleListView.as_view(), name='sale'),
    url(r'^(?P<slug>[\w-]+)/sale/archive$', ShopSaleArchiveView.as_view(), name='sale_archive'),
    url(r'^(?P<slug>[\w-]+)/update/$', ShopUpdateView.as_view(), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', ShopDeleteView.as_view(), name='delete'),
    url(r'^(?P<slug>[\w-]+)/add-banners/$', CreateBanners.as_view(), name='add_banner'),
    url(r'^(?P<slug>[\w-]+)/update-social/$', ShopSocialLinksUpdateView.as_view(), name='update_social'),
    url(r'^$', ShopListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/review/$', ShopReviewListView.as_view(), name='review'),
    url(r'^(?P<slug>[\w-]+)/add-review/$', add_shop_review, name='add_review'),
    url(r'^(?P<slug>[\w-]+)/update-review/(?P<pk>[0-9]+)/$', update_shop_review, name='update_review'),

]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views import defaults as default_views
from apps.global_category.views import IndexView, landing
from apps.product.views import FavoriteCreateView, product_reviews, change_publish_status
from apps.index.views import IndexView, HelpView
from apps.product.views import FavoriteCreateView, product_reviews
from apps.shop.views import agreement, shop_reviews
from apps.product.views import search_predict_html, search
from apps.utils.views import counter
from apps.users.views import SubscribeListView
from apps.category.views import mail_confirm_view
from config.settings.sitemap import ProductSitemap, ShopSitemap, SectionSitemap, CategorySitemap
from django.contrib.sitemaps.views import sitemap
from apps.meta.views import ClaimCreate

sitemaps = {
    'sections': SectionSitemap,
    'category': CategorySitemap,
    'products': ProductSitemap,
    'shops': ShopSitemap,

}

urlpatterns = [
                  url(r'^$', IndexView.as_view(), name='home'),
                  url(r'^change_publish_status/$', change_publish_status, name='change_publish_status'),
                  url(r'^api/v1/', include('apps.api.v1.urls', namespace='api')),
                  url(r'^docs/', include('rest_framework_docs.urls')),
                  url(r'^favorite/add/', FavoriteCreateView.as_view(), name="create_favorite"),
                  url(r'^shops/', include('apps.shop.urls', namespace='shops')),
                  url(r'^order/', include('apps.order.urls', namespace='order')),
                  url(r'^cart/', include('apps.cart.urls', namespace='cart')),
                  url(r'^product/', include('apps.product.urls', namespace='product')),
                  url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
                  url(r'^help/$', HelpView.as_view(), name='help'),
                  url(r'^agreement/$', agreement, name='agreement'),
                  url(r'^search_predict_html', search_predict_html, name='search_predict_html'),
                  url(r'^sub-list/$', SubscribeListView.as_view(), name='sub_list'),
                  url(r'^counter/$', counter, name='counter'),
                  url(r'^search_results', search_predict_html),
                  url(r'^search', search),
                  url(r'^ckeditor/', include('ckeditor_uploader.urls')),
                  url(r'^landing/', ClaimCreate.as_view(), name='landing'),
                  url(r'^landing_clients/', lambda r: render(r, 'layout/landing_clients.html'), name='landing_cli'),
                  url(r'^product_reviews/$', product_reviews, name='product_reviews'),
                  url(r'^shop_reviews/$', shop_reviews, name='shop_reviews'),
                  url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

                  # Django Admin, use {% url 'admin:index' %}
                  url(r'^jet/', include('jet.urls', 'jet')),
                  url(settings.ADMIN_URL, admin.site.urls),

                  # User management
                  url(r'^users/', include('apps.users.urls', namespace='users')),
                  url(r'^accounts/', include('allauth.urls')),
                  url(r'^b85b738ce8c6.html/', mail_confirm_view),
                  url(r'^mailru-domainW2v3UzKC1xMpwEYv.html', TemplateView.as_view(template_name='mailru-domainW2v3UzKC1xMpwEYv.html')),
                  url(r'^', include('apps.category.urls', namespace='categories')),

                  # Your stuff: custom urls includes go here

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
                          url(r'^__debug__/', include(debug_toolbar.urls)),
                      ] + urlpatterns

apps/cart/models.py
from decimal import Decimal
from django.db import models

# Create your models here.
from django.db.models.signals import pre_save, post_save, post_delete

from apps.product.models import Product
from apps.shop.models import Shop
from apps.users.models import User
from django.utils.translation import ugettext as _
from apps.utils.models import PublishBaseModel


class Cart(PublishBaseModel):

    class Meta:
        verbose_name = "Корзина"
        verbose_name_plural = "Корзины"

    user = models.ForeignKey(User, null=True, blank=True, verbose_name="Владелец")
    subtotal = models.DecimalField(max_digits=50, decimal_places=2, default=0.00)
    total = models.DecimalField(max_digits=50, decimal_places=2, default=0.00)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

    def get_delivery_total(self):
        delivery_total = 0
        for index, shop in enumerate(range(self.get_shops().count())):
            if index == 0:
                delivery_total += 150
            else:
                delivery_total += 100
        return delivery_total


    def update_subtotal(self):
        subtotal = 0
        items = self.cartitem_set.all()
        for item in items:
            subtotal += item.total
        subtotal += self.get_delivery_total()
        self.subtotal = "%.2f" % (subtotal)
        self.save()

    def subtotal_for_shop(self, shop):
        subtotal = 0

        for item in self.cartitem_set.filter(product__shop=shop):
            subtotal += item.total

        # subtotal += self.get_delivery_total()
        return "%.2f" % (subtotal)

    def get_shops(self):
        products = self.cartitem_set.all()
        product_ids = [product.product.id for product in products]
        shops = Shop.objects.filter(product__id__in=product_ids).distinct()
        return shops

    def empty(self):
        for item in self.cartitem_set.all():
            item.delete()

    def get_cart_items_count(self):
        return self.cartitem_set.count()


class CartItem(models.Model):

    class Meta:
        verbose_name = "Продукт в корзине"
        verbose_name_plural = "Продукты в корзине"

    cart = models.ForeignKey(Cart, verbose_name='Корзина')
    product = models.ForeignKey(Product, verbose_name='Продукт', null=True, blank=True)
    quantity = models.PositiveIntegerField(_("Количество"), default=1)
    comments = models.TextField(_("Комментарии к продукту"), null=True, blank=True)
    total = models.DecimalField(_("Общая цена"), max_digits=10, decimal_places=2)

    def __str__(self):
        return self.product.title

    def get_shops(self):
        products = self.product.all()
        product_ids = [product.product.id for product in products]
        shops = Shop.objects.filter(product__id__in=product_ids).distinct()
        return shops

def cart_item_pre_save_receiver(sender, instance, *args, **kwargs):
    qty = instance.quantity
    if int(qty) >= 1:
        price = instance.product.get_price()
        total = Decimal(qty) * Decimal(price)
        instance.total = "%.2f" % (total)

pre_save.connect(cart_item_pre_save_receiver, sender=CartItem)


def cart_item_post_save_receiver(sender, instance, *args, **kwargs):
    instance.cart.update_subtotal()

post_save.connect(cart_item_post_save_receiver, sender=CartItem)

post_delete.connect(cart_item_post_save_receiver, sender=CartItem)

apps/cart/views.py
import os
from django.http import JsonResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import DetailView
from apps.product.models import Product
from apps.shop.models import Shop
from .models import Cart, CartItem
from django.views import View
from .mixins import CartOwnerUsers, ConfirmOrderByShopOwner


# Create your views here.

def get_summ(items):
    total = 0
    for i in items:
        total += i.total
    return total


class CartDetailView(SingleObjectMixin, View):
    model = Cart
    template_name = "cart/cart_detail.html"

    def get_object(self, *args, **kwargs):
        self.request.session.set_expiry(0)  # 5 minutes
        cart_id = self.request.session.get("cart_id", "")
        if cart_id == "":
            cart = Cart()
            cart.save()
            cart_id = cart.id
            self.request.session["cart_id"] = cart_id
        cart = Cart.objects.get(id=cart_id)
        if self.request.user.is_authenticated():
            cart.user = self.request.user
            cart.save()
        return cart

    def get(self, request, *args, **kwargs):
        cart = self.get_object()
        # shops = cart.get_shops()
        # total_by_shop = dict()
        # for shop in shops:
        #     items = cart.cartitem_set.filter(product__shop=shop)
        #     total_by_shop[shop.title] = get_summ(items)
        item_id = request.GET.get("item", "")
        delete_item = request.GET.get("delete", False)
        flash_message = ""
        item_added = False
        if item_id:
            item_instance = get_object_or_404(Product, id=item_id)
            qty = request.GET.get("qty", 1)
            cart_item, created = CartItem.objects.get_or_create(cart=cart, product=item_instance)
            try:
                if int(qty) < 1 or not created and cart_item.quantity == qty:
                    delete_item = True
            except:
                raise Http404


            if created:
                flash_message = "Продукт успешно добавлен в корзину"
                item_added = True
            # elif not created and cart_item.quantity == qty:
            #     delete_item = True
            if not created and qty == 1:
                flash_message = "Продукт успешно удален из корзины"
                cart_item.delete()
            else:
                if not created:
                    flash_message = "Количество продукта изменено"
                cart_item.quantity = qty
                text = request.GET.get('text', "")
                if text:
                    cart_item.comments = text
                cart_item.save()
            if not request.is_ajax():
                return HttpResponseRedirect(reverse("cart:detail"))
                # return cart_item.cart.get_absolute_url()

        if request.is_ajax():
            try:
                total = cart_item.total
            except:
                total = None
            try:
                id = cart_item.product.id
            except:
                id = None
            try:
                subtotal = cart_item.cart.subtotal
            except:
                subtotal = None

            try:
                cart_total = cart_item.cart.total
            except:
                cart_total = None

            try:
                total_items = cart_item.cart.cartitem_set.count()
            except:
                total_items = 0

            data = {
                "deleted": delete_item,
                "item_added": item_added,
                "line_total": total,
                "subtotal": subtotal,
                "cart_total": cart_total,
                "flash_message": flash_message,
                "total_items": total_items,
                "id": id
            }

            return JsonResponse(data)

        context = {
            "object": self.get_object()
        }
        template = self.template_name
        return render(request, template, context)


class CartDetailByPkUser(CartOwnerUsers, View):
    def get(self, request, *args, **kwargs):
        cart = get_object_or_404(Cart, id=kwargs.get('pk', ''))
        if cart.user == request.user or request.user.is_staff:
            template = 'cart/cart_detail_user.html'
            context = dict(object=cart)
            return render(request, template, context)
        else:
            raise Http404

    def post(self, request, *args, **kwargs):
        cart = get_object_or_404(Cart, id=kwargs.get('pk', ''))
        all_cartitems = cart.cartitem_set.values_list('id', flat=True)
        cartitems_ids = [int(i) for i in request.POST.getlist('item')]
        cartitem_text = request.POST.getlist('text')
        cartitem_qty = [int(q) for q in request.POST.getlist('qty')]
        combine_values = list(zip(cartitems_ids, cartitem_text, cartitem_qty))
        deleted_ids = list(set(all_cartitems).difference(set(cartitems_ids)))
        if deleted_ids:
            cart.cartitem_set.filter(id__in=deleted_ids).delete()
        for i, t, q in combine_values:
            cartitem = get_object_or_404(CartItem, id=i)
            if q < 1:
                cartitem.delete()
            else:
                cartitem.comments = t.strip()
                cartitem.quantity = q
                cartitem.save()
        return HttpResponseRedirect(reverse('cart:detail_by_pk_user', kwargs={'pk': cart.id,
                                                                              'username': request.user.username}))


class CartDetailByPkShop(CartOwnerUsers, View):
    def get(self, request, *args, **kwargs):
        cart = get_object_or_404(Cart, id=kwargs.get('pk', ''))
        shop = get_object_or_404(Shop, slug=kwargs.get('shop_slug', ''))
        items = cart.cartitem_set.filter(product__shop__user__id=request.user.id)
        if shop in cart.simpleorder.confirm_shops.all():
            status = 'confirmed'
        elif shop in cart.simpleorder.rejected_shops.all():
            status = 'rejected'
        else:
            status = 'none'
        template = 'cart/cart_detail_shops.html'
        context = dict(items=items, total_price=sum(items.values_list('total', flat=True)),
                       shop=shop, status=status)
        return render(request, template, context)


class ConfirmOrderByShop(ConfirmOrderByShopOwner, View):
    def post(self, request, *args, **kwargs):
        flag = request.POST.get('flag')
        cart = get_object_or_404(Cart, id=kwargs.get('pk', ''))
        shop_slug = request.POST.get('shop_slug', '')
        order = cart.simpleorder
        shop = get_object_or_404(Shop, slug=shop_slug)
        if order and flag:
            if flag == 'confirm':
                order.rejected_shops.remove(shop)
                order.confirm_shops.add(shop)
                order.save()
                return JsonResponse({'status': 0, 'message': 'Заказ успешно подтвержден.'})
            else:
                order.confirm_shops.remove(shop)
                order.rejected_shops.add(shop)
                order.save()
                return JsonResponse({'status': 0, 'message': 'Заказ отклонен.'})
        return JsonResponse({'status': 1, 'message': 'Заказ не найден.'})

templates/cart/cart_detail.html
{% extends 'base-1.html' %}
{% load staticfiles %}
{% block categories %}
{% endblock %}


{% block content %}


    <section class="basket-page uk-margin-medium-top">
        <div class="uk-container">
            <div class="shadow  uk-padding-small">
                {% for shop in object.get_shops %}

                    <div class="cync-shop uk-grid">
                        <div class="image-magazin uk-width-1-5@m">
                            <div class="img-wrapper shadow">
                                <a href="{{ shop.get_absolute_url }}">
                                    <img src="{{ shop.get_logo }}" alt="{{ shop.title }}"
                                         class="img-responsive">

                                </a>
                            </div>
                        </div>

                        <div class="uk-width-expand@m" style="">
                            <div class="shadow">
                                <div class="uk-grid">
                                    <div class="uk-width-1-2@m">
                                        <p class="uk-padding-small" style="background: #f1f1f1;padding-left: 40px;">
                                            Товар</p>
                                    </div>
                                    <div class="uk-width-expand@m uk-grid">
                                        <div class="uk-width-1-2@m uk-padding-small" style="background: #f1f1f1;">
                                            <p class="">Количество</p>

                                        </div>
                                        <div class="uk-width-1-2@m uk-padding-small" style="background: #f1f1f1;">
                                            <p class="">Цена</p>

                                        </div>
                                    </div>
                                </div>
                                {#   end head#}
                                {% for item in object.cartitem_set.all %}
                                    {% if item.product.shop == shop %}

                                        <div class="body uk-grid">
                                            <div class="uk-width-1-2@m uk-grid">
                                                <div class="uk-width-1-3@m">
                                                    <div class="uk-padding-small uk-text-center">
                                                        <img src="{{ item.product.get_avatar_image }}" width="50"
                                                             alt="{{ item.product.title }}">
                                                    </div>

                                                </div>
                                                <div class="uk-width-expand@m " style="padding-left: 10px;">
                                                    <h3>
                                                        <a href="{{ item.product.get_absolute_url }}">{{ item.product.title }}</a>
                                                    </h3>
                                                    <p class="description-shop">{{ item.product.short_description }}</p>
                                                    <div class="availability">
                                                        <p>
                                                            Наличие:
                                                            <span class="{% if item.product.availability == "available" %} stock
                                                        {% elif item.product.availability == "waiting" %} expectation
                                                        {% else %} not-stock {% endif %}">{{ item.product.get_availability }}
                                                        </span>
                                                        </p>

                                                    </div>
                                                </div>
                                            </div>
                                            <div class="uk-width-expand@m uk-margin-remove-top uk-grid">
                                                <form action="" class="cart-form uk-width-expand@m uk-grid">
                                                    <input type="hidden" name="item" value="{{ item.product.id }}">
                                                    <div class="uk-width-1-2@m">
                                                        <div class="form-group col-lg-6 col-lg-offset-3">
                                                            <input type="number" class="form-control uk-input item-qty"
                                                                   value="{{ item.quantity }}" name="qty">
                                                        </div>
                                                    </div>
                                                    <div class="uk-width-expand@m">
                                                        <p class="price"
                                                           id="line-total-{{ item.product.id }}">{{ item.total }} {{ item.product.currency }}</p>
                                                    </div>
                                                    <div class="uk-width-auto@m uk-padding-remove-left uk-text-right">
                                                        <a href="{{ item.product.remove_from_cart }}"
                                                           uk-icon="icon: close" title="Удалить" uk-tooltip></a>
                                                    </div>
                                                    <div class="uk-width-1-1@m uk-margin-medium-top">

                                                        <div class="form-group">
                                            <textarea name="" class="form-control uk-textarea item-comment"
                                                      data-product-id="{{ item.product.id }}" id="" cols="30" rows="5"
                                                      placeholder="Ваш коментарий к данному товару">{% if item.comments %}
                                                {{ item.comments }}{% endif %}
                                            </textarea>

                                                        </div>

                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                        <hr class="uk-divider-icon">
                                    {% endif %}
                                {% endfor %}
                                {# end body#}
                            </div>


                        </div>

                        <div class="uk-width-1-1 uk-grid uk-margin-medium-left shadow uk-padding uk-padding-remove-left">
                            <div class="border-top">
                                <div class="col-lg-6">
                                    <h3>Доставка</h3>
                                </div>
                                <div class="col-lg-6">
                                    <h4>{% if forloop.first %}150{% else %}100{% endif %} сом</h4>
                                </div>
                            </div>

                        </div>
                    </div>

                {% endfor %}
                <div class="shadow uk-padding uk-margin-small-top">
                    {% if not object.get_shops %}
                        <h4>Ваша корзина пуста</h4>
                    {% else %}

                        <h5>Итого к оплате</h5>
                        <h5 id="subtotal">{{ object.subtotal }} сом</h5>

                        <div class="col-lg-offset-2 col-lg-10">
                            <a href="#basket-modal" class="uk-button uk-button-default" uk-toggle>Оформить
                                покупку</a>
                             <a href="#delevery" class="uk-button uk-button-default" uk-toggle>Условия доставки</a>

                        </div>
                    {% endif %}
                </div>
            </div>


        </div>
    </section>

    <!-- This is the modal -->
    <div id="basket-modal" uk-modal>
        <div class="uk-modal-dialog basket-modal uk-modal-body">
            <button class="uk-modal-close-default" type="button" uk-close></button>
            <form action="{% url 'order:create' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="cart" value="{{ object }}">
                {% if user.is_authenticated %}
                    <div class="uk-form-controls uk-margin">
                        <input type="text" class="uk-input" placeholder="Имя" name="name"
                               {% if object.user.first_name %}value="{{ object.user.first_name }}"{% endif %}
                               required>
                    </div>

                    <div class="uk-form-controls uk-margin">
                        <input type="text" class="uk-input" placeholder="Фамилия" name="last_name"
                               {% if object.user.last_name %}value="{{ object.user.last_name }}"{% endif %}>
                    </div>
                    <div class="uk-form-controls uk-margin">
                        <input type="text" class="uk-input" placeholder="Номер телефона" name="phone"
                               {% if object.user.phone %}value="{{ object.user.phone }}"{% endif %} required>
                    </div>
                    <div class="uk-form-controls uk-margin">
                        <input type="text" class="uk-input" placeholder="Ваш адрес" name="address"
                               {% if object.user.address %}value="{{ object.user.address }}"{% endif %}
                               required>
                    </div>
                {% else %}
                    <div class="uk-form-controls uk-margin">
                        <input type="text" class="uk-input" placeholder="Имя" name="name" required>
                    </div>

                    <div class="uk-form-controls uk-margin">
                        <input type="text" class="uk-input" placeholder="Фамилия" name="last_name">
                    </div>
                    <div class="uk-form-controls uk-margin">
                        <input type="text" class="uk-input" placeholder="Номер телефона" name="phone"
                               required>
                    </div>
                    <div class="uk-form-controls uk-margin">
                        <input type="text" class="uk-input" placeholder="Ваш адрес" name="address" required>
                    </div>
                {% endif %}
                <button type="submit" class="send uk-button uk-button-default">Отправить</button>
                <button class="uk-modal-close uk-button uk-button-default" type="button">Закрыть</button>
            </form>

        </div>
    </div>

    <!-- This is the modal -->
    <div id="delevery" class="uk-modal-container" uk-modal>
        <div class="uk-modal-dialog basket-modal uk-modal-body">
            <button class="uk-modal-close-default" type="button" uk-close></button>
        </div>
    </div>

    <script>
    $('.item-qty').change(function () {
        var formData = $(this).closest('.cart-form').serialize();
        console.log(formData);
        $.ajax({
            type: "GET",
            url: "/cart/",
            data: formData,
            success: function (data) {
                showFlashMessage(data.flash_message);
                $('.cart-count').text(data.total_items);
                $('#line-total-' + data.id).text(data.line_total + ' сом');
                $('#subtotal').text(data.subtotal + ' сом');
            },
            error: function (response, error) {
                console.log(response);
                console.log(error);
            }
        })
    });
    </script>
{% endblock %}