apps/cart/urls.py
from django.conf.urls import url
from .views import CartDetailView, CartDetailByPkUser, CartDetailByPkShop, ConfirmOrderByShop


urlpatterns = [
    url(r'^user/(?P<username>[\w.@+-]+)/(?P<pk>\d+)/$', CartDetailByPkUser.as_view(), name='detail_by_pk_user'),
    url(r'^shop/(?P<shop_slug>[\w.@+-]+)/(?P<pk>\d+)/$', CartDetailByPkShop.as_view(), name='detail_by_pk_shop'),
    url(r'^(?P<pk>\d+)/confirm/$', ConfirmOrderByShop.as_view(), name='detail_by_pk'),
    url(r'^$', CartDetailView.as_view(), name='detail'),
]

apps/shop/urls.py
from django.conf.urls import url, include

from apps.shop.views import *

# ProductFormView

# from apps.shop.views import shop_add

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/sale/(?P<pk>[0-9]+)/$', sale_detail, name='sale_detail'),
    url(r'^delete-banners/$', delete_banners, name='delete-banners'),
    url(r'^create/$', ShopCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', ShopDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/about-us/$', ShopAboutUsDetailView.as_view(), name='about_us'),
    url(r'^(?P<slug>[\w-]+)/contacts/$', ShopContactsView.as_view(), name='contacts_detail'),
    url(r'^(?P<slug>[\w-]+)/sale/create/$', SalesCreateView.as_view(), name='add_sale'),
    url(r'^(?P<slug>[\w-]+)/sale/(?P<pk>[0-9]+)/update$', SalesUpdateView.as_view(), name='update_sale'),
    url(r'^(?P<slug>[\w-]+)/sale/$', ShopSaleListView.as_view(), name='sale'),
    url(r'^(?P<slug>[\w-]+)/sale/archive$', ShopSaleArchiveView.as_view(), name='sale_archive'),
    url(r'^(?P<slug>[\w-]+)/update/$', ShopUpdateView.as_view(), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', ShopDeleteView.as_view(), name='delete'),
    url(r'^(?P<slug>[\w-]+)/add-banners/$', CreateBanners.as_view(), name='add_banner'),
    url(r'^(?P<slug>[\w-]+)/update-social/$', ShopSocialLinksUpdateView.as_view(), name='update_social'),
    url(r'^$', ShopListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/review/$', ShopReviewListView.as_view(), name='review'),
    url(r'^(?P<slug>[\w-]+)/add-review/$', add_shop_review, name='add_review'),
    url(r'^(?P<slug>[\w-]+)/update-review/(?P<pk>[0-9]+)/$', update_shop_review, name='update_review'),

]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views import defaults as default_views
from apps.global_category.views import IndexView, landing
from apps.product.views import FavoriteCreateView, product_reviews, change_publish_status
from apps.index.views import IndexView, HelpView
from apps.product.views import FavoriteCreateView, product_reviews
from apps.shop.views import agreement, shop_reviews
from apps.product.views import search_predict_html, search
from apps.utils.views import counter
from apps.users.views import SubscribeListView
from apps.category.views import mail_confirm_view
from config.settings.sitemap import ProductSitemap, ShopSitemap, SectionSitemap, CategorySitemap
from django.contrib.sitemaps.views import sitemap
from apps.meta.views import ClaimCreate

sitemaps = {
    'sections': SectionSitemap,
    'category': CategorySitemap,
    'products': ProductSitemap,
    'shops': ShopSitemap,

}

urlpatterns = [
                  url(r'^$', IndexView.as_view(), name='home'),
                  url(r'^change_publish_status/$', change_publish_status, name='change_publish_status'),
                  url(r'^api/v1/', include('apps.api.v1.urls', namespace='api')),
                  url(r'^docs/', include('rest_framework_docs.urls')),
                  url(r'^favorite/add/', FavoriteCreateView.as_view(), name="create_favorite"),
                  url(r'^shops/', include('apps.shop.urls', namespace='shops')),
                  url(r'^order/', include('apps.order.urls', namespace='order')),
                  url(r'^cart/', include('apps.cart.urls', namespace='cart')),
                  url(r'^product/', include('apps.product.urls', namespace='product')),
                  url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
                  url(r'^help/$', HelpView.as_view(), name='help'),
                  url(r'^agreement/$', agreement, name='agreement'),
                  url(r'^search_predict_html', search_predict_html, name='search_predict_html'),
                  url(r'^sub-list/$', SubscribeListView.as_view(), name='sub_list'),
                  url(r'^counter/$', counter, name='counter'),
                  url(r'^search_results', search_predict_html),
                  url(r'^search', search),
                  url(r'^ckeditor/', include('ckeditor_uploader.urls')),
                  url(r'^landing/', ClaimCreate.as_view(), name='landing'),
                  url(r'^landing_clients/', lambda r: render(r, 'layout/landing_clients.html'), name='landing_cli'),
                  url(r'^product_reviews/$', product_reviews, name='product_reviews'),
                  url(r'^shop_reviews/$', shop_reviews, name='shop_reviews'),
                  url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

                  # Django Admin, use {% url 'admin:index' %}
                  url(r'^jet/', include('jet.urls', 'jet')),
                  url(settings.ADMIN_URL, admin.site.urls),

                  # User management
                  url(r'^users/', include('apps.users.urls', namespace='users')),
                  url(r'^accounts/', include('allauth.urls')),
                  url(r'^b85b738ce8c6.html/', mail_confirm_view),
                  url(r'^mailru-domainW2v3UzKC1xMpwEYv.html', TemplateView.as_view(template_name='mailru-domainW2v3UzKC1xMpwEYv.html')),
                  url(r'^', include('apps.category.urls', namespace='categories')),

                  # Your stuff: custom urls includes go here

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
                          url(r'^__debug__/', include(debug_toolbar.urls)),
                      ] + urlpatterns

templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
    <section class="page-404">
        <strong>403!</strong>
        <h1>Доступ закрыт!</h1>
        <a href="/">Перейти на главную страницу</a>
    </section>
{% endblock content %}

templates/b85b738ce8c6.html
d6f52c14811b

templates/base-1.html
{% load staticfiles meta_tags %}
<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#" lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
{#    <meta property="og:image" content="path/to/image.jpg">#}
    {% block meta %}
        {% get_seo_data request object as meta %}
        <meta name="description" content="{{ meta.description }}">
        <meta name="keywords" content="{{ meta.keywords }}">
        <meta name="author" content="Ooba.market.kg">
        <title>{% block title %} {{ meta.title }} {% endblock %}</title>
    {% endblock %}
    <meta name="google-site-verification" content="zgfLUGZfNYyg0rxFUXY253G8Ft1XzWkxUrChLoFz-fc"/>
    <link rel="shortcut icon" href="{% static 'img/favicon/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'img/favicon/apple-touch-icon.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/favicon/apple-touch-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/favicon/apple-touch-icon-114x114.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&amp;subset=cyrillic" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="{% static 'js/main.js' %}"></script>
    <meta name=“mailru-domain” content=“W2v3UzKC1xMpwEYv” />
</head>


<body>
<div class="uk-offcanvas-content">


    {#    {% block fixed_categories %}#}
    {#        {% include 'layout/fixed_categories.html' %}#}
    {#    {% endblock %}#}

    {% block header %}
        {% include 'layout/header.html' %}
    {% endblock %}

    {% block categories %}
    {% endblock %}

    {% block messages %}
        {% if messages %}
            <div class='uk-alert-primary' uk-alert>

                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible"{% endif %}
                                               role='alert'>

                        {{ message|capfirst }}
                        <a class="uk-alert-close" uk-close></a>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endblock messages %}

    {% block content %}


    {% endblock content %}
    {% block footer %}
        <footer class="uk-margin-medium-top shadow">
            <div class="uk-container">
                <div class="uk-grid uk-child-width-expand@l uk-child-width-1-1 uk-child-width-1-2@s uk-child-width-1-3@m"
                     uk-grid>
                    <div>
                        <img src="{% static 'img/Footer-logo.png' %}" width="150" alt="">
                    </div>
                    {% for column in footer_cats %}
                        <div>
                            <h3>Категории</h3>
                            <ul>
                                {% for cat in column %}
                                    <li><a href="{{ cat.get_absolute_url }}">{{ cat.title }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endfor %}
                    <div>
                        <h3>Магазинам</h3>
                        <ul>
                            <li><a href="{% url "landing" %}">Для магазинов</a></li>
                            <li><a href="{% url "shops:create" %}">Добавить магазин</a></li>
                            <li><a href="{% url "sub_list" %}">Лента</a></li>
                        </ul>
                    </div>
                    <div>
                        <h3>Контакты</h3>
                        <ul>
                            <li><a href="{% url "help" %}">Помощь</a></li>
                            <li>+996 550 05 55 77</li>
                            <li>г. Бишкек, ул. Усенбаева 138А</li>
                        </ul>
                    </div>
                </div>

            </div>
        </footer>
        <footer class="bg">
        <div class="uk-container">
            <div class="bottom-line">
                <div class="uk-grid" uk-grid>
                    <div class="uk-width-1-2@s uk-text-left@s uk-text-center">
                        <span>© 2017 Ooba Market</span>
                    </div>
                    <div class="uk-width-1-2@s uk-text-right@s uk-text-center">
                        <a href="http://sunrisestudio.pro/">
                            <img src="{% static 'img/razrabotka.png' %}" alt="">
                        </a>
                    </div>
                </div>
            </div>
        </div>
        </footer>
    {% endblock footer %}
    {% block modal %}

        {#        <div class="modal fade remove-product" id="DeleteModal" tabindex="-1" role="dialog"#}
        {#             aria-labelledby="myModalLabel">#}
        {#            <div class="modal-dialog" role="document">#}
        {#                <div class="modal-content">#}
        {#                    <div class="modal-header">#}
        {#                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span#}
        {#                                aria-hidden="true">&times;</span></button>#}
        {#                        <h4 class="modal-title" id="myModalLabel">Удалить ?</h4>#}
        {##}
        {#                    </div>#}
        {#                    <div class="modal-body" id="ajax-modal-body">#}
        {##}
        {#                    </div>#}
        {#                </div>#}
        {#            </div>#}
        {#        </div>#}

        <!-- This is the modal -->

    {% endblock %}

    {% block js %}
        {% include 'layout/js.html' %}
    {% endblock %}


</div>
{#parent uk-offcanvas-content#}

</body>
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-106324416-1', 'auto');
    ga('send', 'pageview');


    var _search = function (apiUrl, query) {

        if (query.length < 3) {
            let autoComplite = $('.auto-complite');
            autoComplite.attr('hidden', true);
            return
        }


        $.ajax({
            url: apiUrl,
            type: 'GET',
            data: {
                q: query,
            },
            success: function (data) {
                let autoComplite = $('.auto-complite');
                if (autoComplite.length) {
                    autoComplite.remove();
                    $('.search-container').append(data);
                    $('.see-more').attr('href', '/search/?q=' + query);

                } else {
                    $('.search-container').append(data);
                    $('.see-more').attr('href', '/search/?q=' + query);
                }

            }
        });
    };

    $('#search-form-index').bind('keyup paste', function () {
        _search('/search_results/', $(this).val())
    });

    var parseQueryString = function () {

        var str = location.search;
        var objURL = {};

        str.replace(
            new RegExp("([^?=&]+)(=([^&]*))?", "g"),
            function ($0, $1, $2, $3) {
                objURL[$1] = $3;
            }
        );
        return objURL;
    };

    //Example how to use it:
    var params = parseQueryString();
    if (params['q']) {
        $('#search-form-index').val(decodeURIComponent(params['q']));
    }

</script>


</html>

templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Ooba Market{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endblock %}
    <meta name=“mailru-domain” content=“W2v3UzKC1xMpwEYv” />
  </head>

  <body>




  <style>
      .container-alert-flash {
	        position: absolute;
            top: 10px;
            z-index: 50000;
            width: 100%;
            right: 0%;
            margin: 0px;
            display:none;
    }
  </style>

    <div class="m-b-1">
      <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">Ooba Market</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

  <section class="user_update">
    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->
  </section>


    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 Alpha 4 -->
      <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
  </body>
</html>

templates/header.html
{% load staticfiles %}
<header class="navbar-fixed-top">
    <div class="clearfix"></div>
    <nav class="navbar ">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'img/logo.svg' %}" alt="Ooba market">
                    <span><a href="{{ get_absolute_url }}">{{ global_title }}</a></span>
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <div class="nav navbar-nav navbar-right">
                    <form class="form-inline">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Поиск товаров...">
                            <button type="submit" class="btn btn-default">Найти</button>
                        </div>
                    </form>
                 {% if user.is_authenticated %}
                     <a href="{{ user.get_favorites_link }}"  class="favorites btn"><span class="glyphicon glyphicon-heart"></span> Избранные (<span class="favorites_count">{{ user.get_favorites_count }}</span>)</a>
                    <a href="{% url 'cart:detail' %}"  class="basket btn"><span class="glyphicon glyphicon-shopping-cart"></span> Корзина (<span class="cart-count">{{ user.get_cart_count }}</span>)</a>
                    <!-- <a href=""  class="enter btn">Войти</a> -->
                    {% else %}
                    <a href="{% url 'account_login' %}"  class="favorites btn"><span class="glyphicon glyphicon-heart"></span> Избранные</a>
                    <a href="{% url 'cart:detail' %}"  class="basket btn"><span class="glyphicon glyphicon-shopping-cart"></span> Корзина (<span class="cart-count">{{ cart_count }}</span>)</a>
                    <!-- <a href=""  class="enter btn">Войти</a> -->
                {% endif %}
                    <!--
                    Когда вход выполнен!
                    -->
                    {% include 'dropdown.html' %}
                    </div>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
        </div>
    </nav>
    <div class="clearfix"></div>
</header>

templates/mailru-domainW2v3UzKC1xMpwEYv.html
mailru-domain: W2v3UzKC1xMpwEYv

templates/react.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<title>fnnzzz-react-redux-boilerplate</title>
</head>
<body>
	<div id="app_entry"></div>
</body>
</html>