apps/shop/urls.py
from django.conf.urls import url, include

from apps.shop.views import *

# ProductFormView

# from apps.shop.views import shop_add

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/sale/(?P<pk>[0-9]+)/$', sale_detail, name='sale_detail'),
    url(r'^delete-banners/$', delete_banners, name='delete-banners'),
    url(r'^create/$', ShopCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', ShopDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/about-us/$', ShopAboutUsDetailView.as_view(), name='about_us'),
    url(r'^(?P<slug>[\w-]+)/contacts/$', ShopContactsView.as_view(), name='contacts_detail'),
    url(r'^(?P<slug>[\w-]+)/sale/create/$', SalesCreateView.as_view(), name='add_sale'),
    url(r'^(?P<slug>[\w-]+)/sale/(?P<pk>[0-9]+)/update$', SalesUpdateView.as_view(), name='update_sale'),
    url(r'^(?P<slug>[\w-]+)/sale/$', ShopSaleListView.as_view(), name='sale'),
    url(r'^(?P<slug>[\w-]+)/sale/archive$', ShopSaleArchiveView.as_view(), name='sale_archive'),
    url(r'^(?P<slug>[\w-]+)/update/$', ShopUpdateView.as_view(), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', ShopDeleteView.as_view(), name='delete'),
    url(r'^(?P<slug>[\w-]+)/add-banners/$', CreateBanners.as_view(), name='add_banner'),
    url(r'^(?P<slug>[\w-]+)/update-social/$', ShopSocialLinksUpdateView.as_view(), name='update_social'),
    url(r'^$', ShopListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/review/$', ShopReviewListView.as_view(), name='review'),
    url(r'^(?P<slug>[\w-]+)/add-review/$', add_shop_review, name='add_review'),
    url(r'^(?P<slug>[\w-]+)/update-review/(?P<pk>[0-9]+)/$', update_shop_review, name='update_review'),

]

apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(r'^subscribe/$', views.subscribe, name='subscribe'),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<pk>[0-9]+)/favorites/$',
        view=views.UsersFavoritesListView.as_view(),
        name='favorites'
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views import defaults as default_views
from apps.global_category.views import IndexView, landing
from apps.product.views import FavoriteCreateView, product_reviews, change_publish_status
from apps.index.views import IndexView, HelpView
from apps.product.views import FavoriteCreateView, product_reviews
from apps.shop.views import agreement, shop_reviews
from apps.product.views import search_predict_html, search
from apps.utils.views import counter
from apps.users.views import SubscribeListView
from apps.category.views import mail_confirm_view
from config.settings.sitemap import ProductSitemap, ShopSitemap, SectionSitemap, CategorySitemap
from django.contrib.sitemaps.views import sitemap
from apps.meta.views import ClaimCreate

sitemaps = {
    'sections': SectionSitemap,
    'category': CategorySitemap,
    'products': ProductSitemap,
    'shops': ShopSitemap,

}

urlpatterns = [
                  url(r'^$', IndexView.as_view(), name='home'),
                  url(r'^change_publish_status/$', change_publish_status, name='change_publish_status'),
                  url(r'^api/v1/', include('apps.api.v1.urls', namespace='api')),
                  url(r'^docs/', include('rest_framework_docs.urls')),
                  url(r'^favorite/add/', FavoriteCreateView.as_view(), name="create_favorite"),
                  url(r'^shops/', include('apps.shop.urls', namespace='shops')),
                  url(r'^order/', include('apps.order.urls', namespace='order')),
                  url(r'^cart/', include('apps.cart.urls', namespace='cart')),
                  url(r'^product/', include('apps.product.urls', namespace='product')),
                  url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
                  url(r'^help/$', HelpView.as_view(), name='help'),
                  url(r'^agreement/$', agreement, name='agreement'),
                  url(r'^search_predict_html', search_predict_html, name='search_predict_html'),
                  url(r'^sub-list/$', SubscribeListView.as_view(), name='sub_list'),
                  url(r'^counter/$', counter, name='counter'),
                  url(r'^search_results', search_predict_html),
                  url(r'^search', search),
                  url(r'^ckeditor/', include('ckeditor_uploader.urls')),
                  url(r'^landing/', ClaimCreate.as_view(), name='landing'),
                  url(r'^landing_clients/', lambda r: render(r, 'layout/landing_clients.html'), name='landing_cli'),
                  url(r'^product_reviews/$', product_reviews, name='product_reviews'),
                  url(r'^shop_reviews/$', shop_reviews, name='shop_reviews'),
                  url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

                  # Django Admin, use {% url 'admin:index' %}
                  url(r'^jet/', include('jet.urls', 'jet')),
                  url(settings.ADMIN_URL, admin.site.urls),

                  # User management
                  url(r'^users/', include('apps.users.urls', namespace='users')),
                  url(r'^accounts/', include('allauth.urls')),
                  url(r'^b85b738ce8c6.html/', mail_confirm_view),
                  url(r'^mailru-domainW2v3UzKC1xMpwEYv.html', TemplateView.as_view(template_name='mailru-domainW2v3UzKC1xMpwEYv.html')),
                  url(r'^', include('apps.category.urls', namespace='categories')),

                  # Your stuff: custom urls includes go here

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
                          url(r'^__debug__/', include(debug_toolbar.urls)),
                      ] + urlpatterns

apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

SUBSCRIPTION_TYPES = (
    ("all", "Все"),
    ("only_actions", "Акции"),
    ("only_products", "Товары"),
)


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)
    phone = models.CharField(_('Phone number'), null=True, blank=True, max_length=255)
    address = models.CharField('Адресс', null=True, blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_username(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

    def get_favorites_count(self):
        return self.favoriteproduct_set.count()

    def get_favorites(self):
        return self.favoriteproduct_set.all()

    def get_favorites_link(self):
        return reverse("users:favorites", kwargs={'pk': self.pk})

    def get_original_products(self):
        from apps.product.models import Product
        product_ids = list()
        for product in self.favoriteproduct_set.all():
            product_ids.append(product.product.id)
        products = Product.objects.filter(id__in=product_ids)
        return products

    def get_cart_count(self):
        if self.cart_set.all():
            return self.cart_set.last().get_cart_items_count()
        else:
            return 0

    def shops_name(self):
        return self.shop_set.all()

    def shop_titles(self):
        return self.shop_set.all().values('title')


class Subscription(models.Model):
    user = models.ForeignKey(User)
    subscription = models.ForeignKey('shop.Shop', verbose_name='Подписка на магазины', related_name='sub_shops')
    subscription_type = models.CharField(max_length=50, choices=SUBSCRIPTION_TYPES, verbose_name='Тип подписки', default='all')

apps/users/views.py
from allauth.account.models import EmailAddress
from allauth.account.views import EmailView
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect, HttpResponseBadRequest, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render, render_to_response
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, View
from django.db import IntegrityError
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from apps.shop.models import Shop
from .models import User, Subscription
from .mixins import UserPermMixin


class UserDetailView(LoginRequiredMixin, UserPermMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/user_form.html')

    def post(self, request, *args, **kwargs):
        user = self.request.user
        email = self.request.POST.get('email', '')
        if self.request.POST.get('only_email'):
            if '@' not in email:
                return JsonResponse(dict(message='Введите павильный email', status=2))
            try:
                email_address = EmailAddress.objects.create(user=self.request.user, email=email)
            except IntegrityError:
                return JsonResponse(dict(status=1, message="Такой email уже существует."))
            email_count = user.emailaddress_set.count()
            message = "Email успешно добавлен"
            data = dict(emailaddress=email_address.email, email_count=email_count, message=message, status=0)
            return JsonResponse(data)
        elif self.request.POST.get('remove'):
            if user.emailaddress_set.count() == 1:
                message = "Вы не можете удалить единственный email."
                return JsonResponse(dict(message=message, status=1))
            email_address = get_object_or_404(EmailAddress, email=email)
            if email_address.primary is True:
                next_email = user.emailaddress_set.exclude(email=email).first()
                next_email.primary = True
                next_email.save()
            email_address.delete()
            data = dict(message='{} успешно удален.'.format(email), status=0)
            return JsonResponse(data)
        else:
            userform = get_object_or_404(User, username=kwargs['username'])
            if self.request.POST.get('username') is None or self.request.POST.get('username') == "":
                message = "Поле username не может быть пустым."
                messages.add_message(self.request, messages.ERROR, message)
                return HttpResponseRedirect(reverse('users:detail', kwargs={'username': user.username}))
            userform.username = self.request.POST.get('username', '')
            userform.first_name = self.request.POST.get('first_name', '')
            userform.phone = self.request.POST.get('phone', '')
            userform.last_name = self.request.POST.get('last_name', '')
            userform.address = self.request.POST.get('address', '')
            userform.save()
            if email:
                email_address = get_object_or_404(EmailAddress, email=email)
                email_address.primary = True
                email_address.save()
            return HttpResponseRedirect(reverse('users:detail', kwargs={'username': user.username}))


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', 'username', 'first_name', 'last_name']

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UsersFavoritesListView(DetailView):
    model = User
    template_name = 'users/favorites.html'


@csrf_exempt
def subscribe(request):
    if request.user.is_authenticated:
        if request.method == 'POST' and request.is_ajax():
            user = request.user
            shop_slug = request.POST.get('shop_slug', '')
            shop = get_object_or_404(Shop, slug=shop_slug)
            data = dict()
            if not request.POST.get('sub-type'):
                sub_obj, created = Subscription.objects.get_or_create(user=user, subscription=shop)
                if not created:
                    sub_obj.delete()
                    data['message'] = 'Вы отписаны от обновлений'
                    data['status'] = 0
                    return JsonResponse(data)
                data['message'] = 'Подписка оформлена'
                data['status'] = 1
                return JsonResponse(data)
            else:
                sub_type = request.POST.get('sub-type', '')
                try:
                    sub = Subscription.objects.get(user=user, subscription=shop)
                except Subscription.DoesNotExist:
                    return Http404
                sub.subscription_type = sub_type
                sub.save()
                data['message'] = 'Параметры подписки изменены'
                return JsonResponse(data)
        return HttpResponseBadRequest()
    msg = "Для того чтобы подписаться вам необходимо зарегистрироваться."
    messages.add_message(request, messages.INFO, msg)
    return HttpResponse('redirect')


class SubscribeListView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        from django.core.paginator import Paginator

        user = self.request.user
        sub_list = list()
        for sub in user.subscription_set.all():
            if sub.subscription_type == 'only_actions':
                [sub_list.append(item) for item in sub.subscription.sales_set.all().order_by("created_at")]
            elif sub.subscription_type == 'only_products':
                [sub_list.append(item) for item in sub.subscription.product_set.all().order_by("created_at")]
            else:
                [sub_list.append(item) for item in sub.subscription.sales_set.all().order_by("created_at")]
                [sub_list.append(item) for item in sub.subscription.product_set.all().order_by("created_at")]
        sorted_list = sorted(sub_list, key=lambda x: x.created_at, reverse=True)
        p = Paginator(sorted_list, 8)
        pages_count = p.num_pages
        page = self.request.GET.get('page')
        if page and int(page) <= pages_count:
            p = p.page(int(page))
            return render(self.request, 'users/subs.html', {'sub_objects': p.object_list})
        else:
            return render(self.request, 'users/subs.html', {})

    def get(self, request, *args, **kwargs):
        return render(self.request, 'users/sub_list.html', {})

templates/users/favorites.html
{% extends 'base-1.html' %}
{% load product_tags %}

{% block content %}
<section class="product-list uk-margin-medium-top">
    <div class="uk-container">
         <h3 class="uk-margin-medium-bottom">Избранные товары</h3>
     <div class="uk-child-width-1-1 uk-child-width-1-2@s uk-child-width-1-3@m uk-flex-center  uk-child-width-1-4@l uk-grid-small" uk-grid>
        {% if not object.get_original_products %}
            <p style="height: 35vh" class="uk-text-center uk-margin-large-bottom">Вы еще не добавили товары в избранное!</p>
        {% else %}
        {% include 'product/product_list.html' with object_list=object.get_original_products col=3 %}
        {% endif %}
     </div>
    </div>
</section>

{% endblock %}

templates/users/sub_list.html
{% extends 'base-1.html' %}
{% load product_tags staticfiles %}
{% block content %}
    {% load class_name %}
    <section class="product-list uk-margin-medium-top" id="go-to-top-sub">
    <div class="uk-container">
        <h3 class="uk-margin-medium-bottom"><a href="">Ссылка на магазин лента</a></h3>
        <div class="uk-child-width-1-1 uk-child-width-1-2@s uk-child-width-1-2@m  uk-child-width-1-4@l uk-grid-small sub-list" uk-grid>


            </div>
        </div>
        <div id="stop"></div>
        <div class="uk-text-center uk-margin-medium-top">
            <a id="scroll-trigger" href="#go-to-top-sub" uk-totop uk-scroll>
                <p>Вверх</p>
            </a>
        </div>
    <div id="stop"></div>

    </section>
{% endblock %}


{% block js %}
    <script src="{% static 'js/common.js' %}"></script>
    <script src="{% static 'js/sub_list.js' %}"></script>
{% endblock js %}

templates/users/subs.html
{% load product_tags class_name %}

{% for sub in sub_objects %}

    {% if sub|class_name == "Sales" %}
        <div class="sub-sale">
            <div class="uk-card uk-card-default">
                <span class="descount">{{ sub.discount }}%</span>
                <div class="uk-card-media-top uk-cover-container">
                    <img src="{{ sub.image.url }}" alt="" uk-cover>
                    <canvas width="400" height="400"></canvas>
                </div>
                <div class="uk-card-body uk-padding-small">
                    <h3 class="uk-card-title">{{ sub.title }}</h3>
                   {{ sub.description|safe }}
                    <div class="control-button">
                        <a href="{% url 'shops:sale_detail' slug=sub.shop.slug pk=sub.pk %}" class="uk-button-default uk-button">Просмотреть</a>
                    </div>
                </div>
            </div>
        </div>

{#        <div class="col-md-6">#}
{#            <span class="descount">{{ sub.discount }}%</span>#}
{#            <div class="img-wrapper">#}
{#                <img src="{{ sub.image.url }}" alt="">#}
{#            </div>#}
{#            <div class="description">#}
{#                <h3>{{ sub.title }}</h3>#}
{#                <p>{{ sub.description }}</p>#}
{#                <a class="btn add" href="{% url 'shops:sale_detail' slug=sub.shop.slug pk=sub.pk %}">Просмотреть</a>#}
{#            </div>#}
{#        </div>#}

    {% elif sub|class_name == "Product" %}
        <div class="uk-grid-match item">
            <div class="shadow uk-text-center">
                <div class="uk-inline-clip uk-transition-toggle">
                    <div class="border">
                        <a href="{{ sub.get_absolute_url }}" class="uk-position-cover"></a>
                        <div class="uk-cover-container">
                            <img uk-cover src="{{ sub.get_all_images.first.image.url }}" alt="">
                            <canvas class="uk-visible@s" width="400" height="500"></canvas>
                            <canvas class="uk-hidden@s" width="200" height="300"></canvas>

                        </div>
                    </div>
                    <div class="uk-transition-fade uk-position-cover uk-overlay uk-overlay-default">
                        <a href="{{ sub.get_absolute_url }}" class="uk-position-cover"></a>
                        <small class="uk-display-block">Магазин</small>
                        <h4 class="uk-margin-remove"><a
                                href="{% url 'shops:detail' slug=sub.shop.slug %}"> {{ sub.shop.title }}</a></h4>
                        <p>{{ sub.short_description }}</p>
                        <div class="control uk-visible@s">
                            <a href="#" class="favorite uk-margin-medium-right {% is_favorite_for_like sub request.user %}" data-product-id="{{ sub.id }}" title="{% is_favorite_for_tooltip sub request.user %}" uk-tooltip>
                                <span class=" uk-icon" uk-icon="icon: heart; ratio: 2"></span>
                            </a>
                            {% cart_message request sub %}
                        </div>
                    </div>
                </div>
                <div class="uk-visible@s uk-padding-small uk-grid uk-margin-remove footer">
                    <h4 class="uk-width-3-5@l uk-width-3-5@m uk-padding-remove">{{ sub.title }}</h4>
                    <div class="uk-width-2-5@l uk-text-right uk-width-2-5@m uk-padding-remove">
                        <p>{{ sub.price }} {{ sub.currency }}</p>
                    </div>
                </div>
                <div class="uk-hidden@s uk-padding-small uk-position-relative  uk-grid uk-margin-remove footer">
                     <div class="control uk-hidden@s uk-text-right">
                            <a href="#" class="favorite {% is_favorite_for_like sub request.user %}" data-product-id="{{ sub.id }}" title="{% is_favorite_for_tooltip sub request.user %}" uk-tooltip>
                                <span class=" uk-icon" uk-icon="icon: heart; ratio: 2"></span>
                            </a>
                            {% cart_message request sub %}
                        </div>
                    <h4 style="height: auto;" class="uk-hidden@s uk-margin-small-bottom uk-text-left uk-padding-remove"><b><a style="color: #444; font-size: 15px;" href="{% url 'shops:detail' slug=sub.shop.slug %}">{{ sub.shop.title }}</a></b></h4>
                    <h4 style="height: auto;" class="uk-width-3-5@l uk-text-left uk-width-3-5@m uk-padding-remove">{{ sub.title }}</h4>
                    <div class="uk-width-2-5@l uk-text-left uk-width-2-5@m uk-padding-remove">
                        <p class="uk-text-left">{{ sub.price }} {{ sub.currency }}</p>
                    </div>
                </div>
            </div>
        </div>

{#        <div class="col-md-4 product">#}
{#            <div class="box-shadow">#}
{#                <div class="img-wrapper">#}
{#                    <a href="{{ sub.get_absolute_url }}" class="url-shop"></a>#}
{#                    {% if discount %}#}
{#                        <span class="descount">{{ sub.discount }}%</span>#}
{#                    {% endif %}#}
{#                    <a href="{{ sub.get_absolute_url }}">#}
{#                        <img src="{{ sub.get_all_images.first.image.url }}" alt="">#}
{#                    </a>#}
{#                    <div class="back-fade">#}
{#                        <div class="name-magazin-title">#}
{#                            <h2>#}
{#                                <a href="{% url 'shops:detail' slug=sub.shop.slug %}">#}
{#                                    {{ sub.shop.title }}#}
{#                                </a>#}
{#                            </h2>#}
{#                            <p>{{ sub.short_description }}</p>#}
{#                        </div>#}
{#                        <div class="button-basket-favorite">#}
{#                            {% cart_message request sub %}#}
{#                            <span class="glyphicon glyphicon-heart enable#}
{#                            {% is_favorite_for_like sub request.user %}"#}
{#                                  data-toggle="tooltip"#}
{#                                  data-placement="top"#}
{#                                  data-product-id="{{ sub.id }}"#}
{#                                  data-original-title="{% is_favorite_for_tooltip sub request.user %}">#}
{#                        </span>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="description">#}
{#                    <div class="title">#}
{#                        <h3>{{ sub.title }}</h3>#}
{#                        <p>{{ sub.short_description }}</p>#}
{#                    </div>#}
{#                    <span>{{ sub.price }} {{ sub.currency }}</span>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}



    {% endif %}
{% endfor %}

<script>
    // ---------------------------------
    // функция добавление в избранные на главной
    // ---------------------------------

    $(".favorite").click(function (event) {
        event.preventDefault();
        var thisIcon = $(this);
        var productId = $(this).attr("data-item-id");
        $.ajax({
            type: "GET",
            url: "/favorite/add",
            data: {
                'item': productId
            },
            success: function (data) {
                showFlashMessage(data.flash_message);
                if (data.created) {
                    thisIcon.toggleClass("like");
                    thisIcon.attr("title", "Удалить из избранных");
                }
                else {
                    thisIcon.removeClass("like");
                    thisIcon.attr("title", "Добавить в избранное");
                    if (thisIcon.parent().parent().parent().parent().parent().parent().hasClass('favorite-products')) {
                        thisIcon.parent().parent().parent().parent().fadeOut();
                    }
                }
                $('.favorites_count').html('<span class="uk-margin-small-right uk-icon" uk-icon="icon: heart"></span> Избранные' +
                                    '(<span>' + data.favorites_count + '</span>)')
            },
            error: function (response, error) {
                console.log(response);
                console.log(error);
            }
        })
    });


    // ---------------------------------
    // функция добавление в корзину на главной
    // ---------------------------------

    $(".cart").click(function (event) {
        event.preventDefault();
        var thisIcon = $(this);
        var productId = $(this).attr("data-item-id");
        $.ajax({
            type: "GET",
            url: "/cart/",
            data: {
                'item': productId
            },
            success: function (data) {
                showFlashMessage(data.flash_message);
                if (data.item_added) {
                    thisIcon.toggleClass("in");
                    thisIcon.attr("title", "В корзине");
                }
                else {
                    thisIcon.removeClass("in");
                    thisIcon.attr("title", "Добавить в корзину");
                }
                $('.cart_count').html('<span class="uk-margin-small-right uk-icon" uk-icon="icon: cart"></span> Корзина' +
                                    '(<span>' + data.total_items + '</span>)')
            },
            error: function (response, error) {
                console.log(response);
                console.log(error);
            }
        })
    });

    function showFlashMessage(message) {
        var template = "<div class='uk-container flash'>" +
            "<div class='uk-alert-primary' uk-alert> " +
            "<div class=''>" +
            "<a class='uk-alert-close' uk-close></a>"
            + message + "</div></div></div>";
        $("body").append(template);
        $(".uk-container.flash").fadeIn();
        setTimeout(function () {
            $(".uk-container.flash").fadeOut();
        }, 1800);

    }
</script>

templates/users/user_detail.html
{% extends "base-1.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}

    <section class="user-detail">
        <div class="container">
        <h1>Личный кабинет</h1>
        {% if object == request.user %}
        <!-- Action buttons -->

            <a class="btn" href="{% url 'users:update' %}" role="button">Профиль</a>
            <a class="btn" href="{% url 'account_email' %}" role="button">E-Mail</a>
            <!-- Your Stuff: Custom user template urls -->

        <!-- End Action buttons -->
        {% endif %}

        <h2>{{ object.get_full_name }} </h2>
          {% if object.name %}
              <p><strong>Логин:</strong> {{ object.name }}</p>
            <p><strong>Имя:</strong> {{ object.first_name }}</p>
            <p><strong>Фамилия:</strong> {{ object.last_name }}</p>
            <p><strong>Дата регистрации:</strong> {{ object.date_joined }}</p>
          {% endif %}



        </div>
    </section>

{% endblock content %}

templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}