apps/cart/urls.py
from django.conf.urls import url
from .views import CartDetailView, CartDetailByPkUser, CartDetailByPkShop, ConfirmOrderByShop


urlpatterns = [
    url(r'^user/(?P<username>[\w.@+-]+)/(?P<pk>\d+)/$', CartDetailByPkUser.as_view(), name='detail_by_pk_user'),
    url(r'^shop/(?P<shop_slug>[\w.@+-]+)/(?P<pk>\d+)/$', CartDetailByPkShop.as_view(), name='detail_by_pk_shop'),
    url(r'^(?P<pk>\d+)/confirm/$', ConfirmOrderByShop.as_view(), name='detail_by_pk'),
    url(r'^$', CartDetailView.as_view(), name='detail'),
]

apps/order/urls.py
from apps.order.views import OrderDetail, SimpleOrderCreateView, ThankYouView, UserSimpleOrderListView, \
    ShopSimpleOrderUpdateView, ShopSimpleOrderDetailView, ShopSimpleOrderListView, \
    shop_change_status, UserSimpleOrderDetailView, shop_delete_cartitem_product, SimpleOrderListViewForModers, \
    SendLetterToCurier
from django.conf.urls import url

urlpatterns = [
    url(r'^create/$', SimpleOrderCreateView.as_view(), name='create'),
    url(r'^thank-you/$', ThankYouView.as_view(), name="thanks"),
    url(r'^change_status/$', shop_change_status, name='change_status'),
    url(r'^delete_product/$', shop_delete_cartitem_product, name='delete_product'),
    url(r'^(?P<slug>[\w.@+-]+)/order-list/$', ShopSimpleOrderListView.as_view(), name='shop_order_list'),
    url(r'^(?P<slug>[\w.@+-]+)/order-detail/(?P<pk>\d+)/$', ShopSimpleOrderDetailView.as_view(),
        name='shop_simple_order_detail'),
    url(r'^(?P<pk>\d+)/order_update$', ShopSimpleOrderUpdateView.as_view(), name='shop_simple_order_update'),
    # url(r'^(?P<pk>\d+)/delete/$', DeleteSimpleOrderShop.as_view(), name='shop_order_delete'),
    # url(r'^(?P<pk>\d+)/$', OrderDetail.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/user_detail$', UserSimpleOrderDetailView.as_view(), name='user_order_detail'),
    url(r'^moderator/(?P<username>[\w.@+-]+)/order-list/send_order/$', SendLetterToCurier.as_view(), name='send_curier'),
    url(r'^moderator/(?P<username>[\w.@+-]+)/order-list/$', SimpleOrderListViewForModers.as_view(), name='mod_order_list'),
    url(r'^(?P<username>[\w.@+-]+)/order_list/$', UserSimpleOrderListView.as_view(), name='user_order_list'),

]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views import defaults as default_views
from apps.global_category.views import IndexView, landing
from apps.product.views import FavoriteCreateView, product_reviews, change_publish_status
from apps.index.views import IndexView, HelpView
from apps.product.views import FavoriteCreateView, product_reviews
from apps.shop.views import agreement, shop_reviews
from apps.product.views import search_predict_html, search
from apps.utils.views import counter
from apps.users.views import SubscribeListView
from apps.category.views import mail_confirm_view
from config.settings.sitemap import ProductSitemap, ShopSitemap, SectionSitemap, CategorySitemap
from django.contrib.sitemaps.views import sitemap
from apps.meta.views import ClaimCreate

sitemaps = {
    'sections': SectionSitemap,
    'category': CategorySitemap,
    'products': ProductSitemap,
    'shops': ShopSitemap,

}

urlpatterns = [
                  url(r'^$', IndexView.as_view(), name='home'),
                  url(r'^change_publish_status/$', change_publish_status, name='change_publish_status'),
                  url(r'^api/v1/', include('apps.api.v1.urls', namespace='api')),
                  url(r'^docs/', include('rest_framework_docs.urls')),
                  url(r'^favorite/add/', FavoriteCreateView.as_view(), name="create_favorite"),
                  url(r'^shops/', include('apps.shop.urls', namespace='shops')),
                  url(r'^order/', include('apps.order.urls', namespace='order')),
                  url(r'^cart/', include('apps.cart.urls', namespace='cart')),
                  url(r'^product/', include('apps.product.urls', namespace='product')),
                  url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
                  url(r'^help/$', HelpView.as_view(), name='help'),
                  url(r'^agreement/$', agreement, name='agreement'),
                  url(r'^search_predict_html', search_predict_html, name='search_predict_html'),
                  url(r'^sub-list/$', SubscribeListView.as_view(), name='sub_list'),
                  url(r'^counter/$', counter, name='counter'),
                  url(r'^search_results', search_predict_html),
                  url(r'^search', search),
                  url(r'^ckeditor/', include('ckeditor_uploader.urls')),
                  url(r'^landing/', ClaimCreate.as_view(), name='landing'),
                  url(r'^landing_clients/', lambda r: render(r, 'layout/landing_clients.html'), name='landing_cli'),
                  url(r'^product_reviews/$', product_reviews, name='product_reviews'),
                  url(r'^shop_reviews/$', shop_reviews, name='shop_reviews'),
                  url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

                  # Django Admin, use {% url 'admin:index' %}
                  url(r'^jet/', include('jet.urls', 'jet')),
                  url(settings.ADMIN_URL, admin.site.urls),

                  # User management
                  url(r'^users/', include('apps.users.urls', namespace='users')),
                  url(r'^accounts/', include('allauth.urls')),
                  url(r'^b85b738ce8c6.html/', mail_confirm_view),
                  url(r'^mailru-domainW2v3UzKC1xMpwEYv.html', TemplateView.as_view(template_name='mailru-domainW2v3UzKC1xMpwEYv.html')),
                  url(r'^', include('apps.category.urls', namespace='categories')),

                  # Your stuff: custom urls includes go here

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
                          url(r'^__debug__/', include(debug_toolbar.urls)),
                      ] + urlpatterns

apps/order/models.py
from decimal import Decimal
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save, post_save
# Create your models here.
from django.template.loader import get_template, render_to_string

from apps.cart.models import Cart
from apps.product.models import Product
from apps.shop.models import Shop
from apps.users.models import User
from apps.utils.models import PublishBaseModel

import braintree

if settings.DEBUG:
    braintree.Configuration.configure(braintree.Environment.Sandbox,
                                      merchant_id=settings.BRAINTREE_MERCHANT_ID,
                                      public_key=settings.BRAINTREE_PUBLIC,
                                      private_key=settings.BRAINTREE_PRIVATE)


class UserCheckout(models.Model):
    user = models.OneToOneField(User, null=True, blank=True)  # not required
    email = models.EmailField(unique=True)  # --> required
    braintree_id = models.CharField(max_length=120, null=True, blank=True)

    def __str__(self):
        return self.email

    @property
    def get_braintree_id(self, ):
        instance = self
        if not instance.braintree_id:
            result = braintree.Customer.create({
                "email": instance.email,
            })
            if result.is_success:
                instance.braintree_id = result.customer.id
                instance.save()
        return instance.braintree_id

    def get_client_token(self):
        customer_id = self.get_braintree_id
        if customer_id:
            client_token = braintree.ClientToken.generate({
                "customer_id": customer_id
            })
            return client_token
        return None


def update_braintree_id(sender, instance, *args, **kwargs):
    if not instance.braintree_id:
        instance.get_braintree_id


post_save.connect(update_braintree_id, sender=UserCheckout)

ADDRESS_TYPE = (
    ('billing', 'Billing'),
    ('shipping', 'Shipping'),
)


class UserAddress(models.Model):
    user = models.ForeignKey(UserCheckout)
    type = models.CharField(max_length=120, choices=ADDRESS_TYPE)
    street = models.CharField(max_length=120)
    city = models.CharField(max_length=120)

    def __str__(self):
        return self.street

    def get_address(self):
        return "%s, %s, %s %s" % (self.street, self.city, self.state, self.zipcode)


ORDER_STATUS_CHOICES = (
    ('created', 'Новый'),
    ('processed', 'Обработан'),
)


class Order(models.Model):
    status = models.CharField(max_length=120, choices=ORDER_STATUS_CHOICES, default='created')
    cart = models.ForeignKey(Cart)
    user = models.ForeignKey(UserCheckout, null=True)
    billing_address = models.ForeignKey(UserAddress, related_name='billing_address', null=True)
    shipping_address = models.ForeignKey(UserAddress, related_name='shipping_address', null=True)
    shipping_total_price = models.DecimalField(max_digits=50, decimal_places=2, default=5.99)
    order_total = models.DecimalField(max_digits=50, decimal_places=2, )
    order_id = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return str(self.cart.id)

    class Meta:
        ordering = ['-id']

    def get_absolute_url(self):
        return reverse("order:detail", kwargs={"pk": self.pk})

    def mark_completed(self, order_id=None):
        self.status = "paid"
        if order_id and not self.order_id:
            self.order_id = order_id
        self.save()


def order_pre_save(sender, instance, *args, **kwargs):
    shipping_total_price = instance.shipping_total_price
    cart_total = instance.cart.total
    order_total = Decimal(shipping_total_price) + Decimal(cart_total)
    instance.order_total = order_total


pre_save.connect(order_pre_save, sender=Order)


class SimpleOrder(PublishBaseModel):
    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"
        ordering = ['-created_at']

    name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    user = models.ForeignKey(User, blank=True, null=True)
    cart = models.OneToOneField(Cart)
    confirm_shops = models.ManyToManyField(Shop, verbose_name='Подтвержденные магазины', related_name='confirm_shops')
    rejected_shops = models.ManyToManyField(Shop, verbose_name='Отклоненные магазины', related_name='rejected_shops')
    status = models.CharField(max_length=120, choices=ORDER_STATUS_CHOICES, default='created')
    is_visible = models.BooleanField(verbose_name='Не скрыт', default=True)
    comments = models.TextField(verbose_name='Комментарий к заказу', null=True, blank=True)

    def __str__(self):
        return str(self.name) + str(self.last_name)


def send_email_to_shop_owner(sender, instance, *args, **kwargs):
    template_html = 'account/email/email_trigered_by_order.html'
    template_text = 'account/email/email_trigered_by_order.txt'
    shops = instance.cart.get_shops()
    for shop in shops:
        products = Product.objects.filter(shop=shop, cartitem__cart=instance.cart)
        text_content = render_to_string(template_text,
                                        {"name": instance.name + ' ' + instance.last_name,
                                         'date': instance.created_at, 'address': instance.address,
                                         'phone': instance.phone,
                                         'products': products, })
        html_content = render_to_string(template_html,
                                        {"name": instance.name + ' ' + instance.last_name,
                                         'date': instance.created_at, 'address': instance.address,
                                         'phone': instance.phone,
                                         'products': products,
                                         })

        msg = EmailMultiAlternatives('Поступил новый заказ в магазин ' + shop.title, text_content,
                                     settings.EMAIL_HOST_USER, [shop.email])
        msg.attach_alternative(html_content, "text/html")
        msg.send()

# post_save.connect(send_email_to_shop_owner, sender=SimpleOrder)

apps/order/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import UserAddress, SimpleOrder

User = get_user_model()


class GuestCheckoutForm(forms.Form):
    email = forms.EmailField()
    email2 = forms.EmailField(label='Verify Email')

    def clean_email2(self):
        email = self.cleaned_data.get("email")
        email2 = self.cleaned_data.get("email2")

        if email == email2:
            user_exists = User.objects.filter(email=email).count()
            if user_exists != 0:
                raise forms.ValidationError("This User already exists. Please login instead.")
            return email2
        else:
            raise forms.ValidationError("Please confirm emails are the same")


class AddressForm(forms.Form):
    billing_address = forms.ModelChoiceField(
        queryset=UserAddress.objects.filter(type="billing"),
        widget=forms.RadioSelect,
        empty_label=None
    )
    shipping_address = forms.ModelChoiceField(
        queryset=UserAddress.objects.filter(type="shipping"),
        widget=forms.RadioSelect,
        empty_label=None,

    )


class UserAddressForm(forms.ModelForm):
    class Meta:
        model = UserAddress
        fields = [
            'street',
            'city',
            'type'
        ]


class SimpleOrderForm(forms.ModelForm):
    class Meta:
        model = SimpleOrder
        fields = [
            'name',
            'last_name',
            'phone',
            'address',
        ]

    def __init__(self, *args, **kwargs):
        super(SimpleOrderForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(SimpleOrderForm, self).clean()
        name = cleaned_data.get('name', '')
        last_name = cleaned_data.get('last_name', '')
        phone = cleaned_data.get('phone', '')
        address = cleaned_data.get('address', '')

        error_msg = "*Обязательное поле"

        if name is None or name == "":
            self._errors['name'] = error_msg
        if last_name is None or last_name == "":
            self._errors['last_name'] = error_msg
        if phone is None or phone == "":
            self._errors['phone'] = error_msg
        if address is None or address == "":
            self._errors['address'] = error_msg


class ShopSimpleOrderForm(forms.ModelForm):
    class Meta:
        model = SimpleOrder
        fields = [
            'status',
            'comments',
        ]

    def __init__(self, *args, **kwargs):
        super(ShopSimpleOrderForm, self).__init__(*args, **kwargs)
        # self.status = kwargs['initial']['status']

templates/order/order_detail.html
{% extends 'base-1.html' %}

{% block content %}


    <div class="basket-page">
    <div class="container">
        <div class="tab-simpleorder">
        <div class="head">
                    <div class="parets">
                        <ul>
                            <li>
{#                                <label for="parent">#}
{#                                    <input type="checkbox" id="parent">#}
{#                                    <div class="indicator"></div>#}
                                </label>
                            </li>
                            <li>Номер заказа</li>
                            <li>Дата</li>
                            <li>Заказчик</li>
                            <li>Статус</li>
                            <li>Адрес доставки</li>
                            <li>Телефон</li>
                            <li>Сумма доставки</li>
                            <li>Комиссия</li>
                        </ul>

                    </div>
                </div>
        <div class="child-object">
                        <ul>
                            <li>
                                <label for="child">
                                    <input type="checkbox" id="child">
                                    <div class="indicator"></div>
                                </label>
                            </li>
                            <li>{{ object.cart.id }}</li>
                            <li>{{ object.created_at|date:"d.m.y H:i" }}</li>
                            <li>{{ object.name }}</li>
                            <li>
                                <form method="POST"  action="{% url 'order:change_status' %}" class="order_change">
                                    {% csrf_token %}
                                    <select class="form-control " id="id_status"
                                            name="status" required="">
                                        {% for x,y in form.fields.status.choices %}
                                            <option value="{{ x }}"
                                            {% if object.status == x %}selected{% endif %}>{{ y }}</option>
                                        {% endfor %}
                                    </select>
                                    <input type="hidden" name="id" value="{{ object.id }}">
                                    {#<button class="btn" type="submit">Подтвердить</button>#}
                                </form>
                            </li>
                            <li>{{ object.address }}
                            </li>
                            <li>{{ object.phone }}</li>
                            <li>{{ object.cart.subtotal }}</li>
                            <li>0 сом</li>
                        </ul>
                    </div>
        </div>
{#        <h1>Корзина</h1>#}
        <div class="cover">

        </div>
        <div class="thead">
            <div class="col-md-6">
                Товар
            </div>
            <div class="col-md-2">
                Продавец
            </div>
            <div class="col-md-2">
                Количество
            </div>
            <div class="col-md-2">
                Цена
            </div>
        </div>
        <div class="tbody">

            {% for product in object.cart.cartitem_set.all %}

            <div class="cover">
                <div class="col-md-2">
                    <div class="img-wrapper">
                        <img src="{{ product.product.get_main_image }}" alt="{{ product.product.title }}" class="img-responsive">
                    </div>
                </div>
                <div class="col-md-4">
                    <h2><a href="{{ product.product.get_absolute_url }}">{{ product.product.title }}</a></h2>
                    <div class="availability">
                        <span>Наличие: <span class="{% if product.product.availability == "available" %} stock
                                                {% elif product.product.availability == "waiting" %} expectation
                                                {% else %} not-stock {% endif %}">{{ product.product.get_availability }}</span></span>

                        <span class="truck">
                    <i class="fa fa-truck" aria-hidden="true" {% if product.product.delivery_type == 'paid' %} yellow
                    {% elif product.product.delivery_type == 'free' %} green {% endif %}></i>
                    {{ product.product.get_delivery_type }}
                </span>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="img-wrapper">
                        <img src="{{ product.product.shop.get_logo }}" alt="{{ product.product.shop.title }}" class="img-responsive">
                    </div>
                </div>
                <form action="." class="cart-form">
                <input type="hidden" name="item" value="{{ product.product.id }}">
                <div class="col-md-2">
                    <div class="quantity">
                        {{ product.quantity }}
                    </div>

                </div>

                </form>

                <div class="col-md-2 price">
                    {% if product.product.discount %}
                    <strike>{{ product.product.price }} {{ product.product.currency }}</strike>
                    <p id="line-total-{{ product.product.id }}">{{ product.total }} {{ product.product.currency }}</p>
                        {% else %}
                        <p id="line-total-{{ product.product.id }}">{{ product.total }} {{ product.product.currency }}</p>
                    {% endif %}
{#                    <a href="{{ product.product.remove_from_cart }}" class="close">X</a>#}
                </div>
            </div>
            {% endfor %}

            <div class="total">
                <div class="col-md-offset-8 col-md-3">
                    <p>Доставка: <span>0 сом</span></p>
                    <p>Итого: <span class="red" id="subtotal">{{ object.cart.subtotal }} сом </span></p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>





{% endblock %}

templates/order/shop_order_detail.html
{% extends 'base-1.html' %}
{% load widget_tweaks staticfiles%}
{% block content %}


    <div class="basket-page">
        <div class="container">
            {% if form.errors %}
                {{ form.errors }}
            {% endif %}
            <div class="tab-simpleorder">
                <div class="head">
                    <div class="parets">
                        <ul>
                            <li>
                                {#                                <label for="parent">#}
                                {#                                    <input type="checkbox" id="parent">#}
                                {#                                    <div class="indicator"></div>#}
                                </label>
                            </li>
                            <li>Номер заказа</li>
                            <li>Дата</li>
                            <li>Заказчик</li>
                            <li>Статус</li>
                            <li>Адрес доставки</li>
                            <li>Телефон</li>
                            <li>Сумма доставки</li>
                            <li>Комиссия</li>
                        </ul>

                    </div>
                </div>
                <div class="child-object">
                    <form method="POST" action="{% url 'order:shop_simple_order_update' pk=object.pk %}"
                          class="order_change">
                        <ul>
                            <li>
                                <label for="child">a
                                    <input type="checkbox" id="child">
                                    <div class="indicator"></div>
                                </label>
                            </li>
                            <li>{{ object.cart.id }}</li>
                            <li>{{ object.created_at|date:"d.m.y H:i" }}</li>
                            <li>{{ object.name }}</li>
                            <li>

                                {% csrf_token %}
                                <select class="form-control " id="id_status"
                                        name="status" required="">
                                    {% for x,y in form.fields.status.choices %}
                                        <option value="{{ x }}"
                                                {% if object.status == x %}selected{% endif %}>{{ y }}</option>
                                    {% endfor %}
                                </select>
                                <input type="hidden" name="id" value="{{ object.id }}">
                                {#<button class="btn" type="submit">Подтвердить</button>#}

                            </li>
                            <li>{{ object.address }}
                            </li>
                            <li>{{ object.phone }}</li>
                            <li>{{ object.cart.subtotal }}</li>
                            <li>0 сом</li>
                        </ul>
                        Комментарий к заказу: {{ form.comments|attr:"class:form-control" }}
                        <button class="btn add">Сохранить</button>
                    </form>
                </div>
            </div>
            {#        <h1>Корзина</h1>#}
            <div class="cover">

            </div>
            <div class="thead">
                <div class="col-md-6">
                    Товар
                </div>
                <div class="col-md-2">
                    Продавец
                </div>
                <div class="col-md-2">
                    Количество
                </div>
                <div class="col-md-2">
                    Цена
                </div>
            </div>
            <div class="tbody">

                {% for product in object.cart.cartitem_set.all %}

                    <div class="cover">
                        <div class="col-md-2">
                            <div class="img-wrapper">
                                <img src="{{ product.product.get_main_image }}" alt="{{ product.product.title }}"
                                     class="img-responsive">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <h2><a href="{{ product.product.get_absolute_url }}">{{ product.product.title }}</a></h2>
                            <div class="availability">
                        <span>Наличие: <span class="{% if product.product.availability == "available" %} stock
                                                {% elif product.product.availability == "waiting" %} expectation
                                                {% else %} not-stock {% endif %}">{{ product.product.get_availability }}</span></span>

                                <span class="truck">
                    <i class="fa fa-truck" aria-hidden="true" {% if product.product.delivery_type == 'paid' %} yellow
                    {% elif product.product.delivery_type == 'free' %} green {% endif %}></i>
                    {{ product.product.get_delivery_type }}
                </span>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="img-wrapper">
                                <img src="{{ product.product.shop.get_logo }}" alt="{{ product.product.shop.title }}"
                                     class="img-responsive">
                            </div>
                        </div>
                        <form action="." class="cart-form">
                            <input type="hidden" name="item" value="{{ product.product.id }}">
                            <div class="col-md-2">
                                <div class="quantity">
                                    {{ product.quantity }}
                                </div>

                            </div>

                        </form>

                        <div class="col-md-2 price">
                            {% if product.product.discount %}
                                <strike>{{ product.product.price }} {{ product.product.currency }}</strike>
                                <p id="line-total-{{ product.product.id }}">{{ product.total }} {{ product.product.currency }}</p>
                            {% else %}
                                <p id="line-total-{{ product.product.id }}">{{ product.total }} {{ product.product.currency }}</p>
                            {% endif %}
                            <a href="{% url 'order:shop_simple_order_update' pk=object.pk %}" class="close remove_product"
                               name="remove_product" id="{{ product.product.id }}">X</a>
                        </div>
                    </div>
                {% endfor %}

                <div class="total">
                    <div class="col-md-offset-8 col-md-3">
                        <p>Доставка: <span>0 сом</span></p>
                        <p>Итого: <span class="red" id="subtotal">{{ object.cart.subtotal }} сом </span></p>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>





{% endblock %}

{% block js %}
        <script src="{% static 'js/jquery.2.2.4.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/common.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
{% endblock %}

templates/order/thanks.html
{% extends 'base-1.html' %}

{% block content %}
    <section class="thanks uk-margin-medium-top">
        <div class="uk-container">
            <div class="shadow uk-padding uk-text-center">
                <h1>Спасибо что сделали заказ</h1>
                <p>Ваш заказ оформлен,мы оповестили владелеца магазина и он свяжется с Вами</p>
                <p>Если возникли проблемы с работой магазина свяжитесь с нами по email: sunrisestudiopro@gmail.com</p>
                <hr class="uk-divider-icon uk-margin-medium-top">
                <h2>Вы оформили корзину товара</h2>
                <div class="go">
                    {% if user.is_authenticated %}
                        <a class="uk-button-default uk-button"
                           href="{% url 'order:user_order_list' username=request.user.username %}">Посетить историю
                            покупок</a>
                    {% endif %}
                    <a class="uk-button-default next uk-button" href="/">Продолжить покупку</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}